### ISSUE TITLE
Tweaks to "Bees and Trees" Line

### ISSUE THREAD

**Issue by TSKimball** [Yulife/Wanderlust-Reloaded#439]
Compilation of various concerns with the new quest line, from the forum, IRC, running the quests normally (so far), and a full review/read of the HQM page in edit mode.

1) Unable to make the clockwork generator (due to the required gear disabled).  Already a known issue and is being fixed.  Temporary workaround is to cheat in the gear using NEI.

2) The 'Specimen Chests' quest should have the reward bag changed to 1 x Greater, to be in line with other quests of this nature (and the Butterfly chest can be hard/rare to kick off).

3) The 'Balsa' tree quest has 'Making Ethanol' as a requirement.  This sounds odd, please double-check the link.

4) The DNA/Genetics quests appear slightly out of order.  'Incubator Recipes' is before the quest that introduces the Incubator itself (Sequencing DNA), making both of them feel incomplete.  These two should probably be merged.

5) Minor nitpick:  Multifarm could use a little extra fleshing out about how to assemble it (does not appear obvious from the current text), or at least give reference for where to find this information.

**Comment by TSKimball** [comment]
Thought I wrote this correctly; nope.  :p  For #4, should read:  'Incubator Recipes' is _before_ the quest that introduces the Incubator itself (Sequencing DNA).

**Comment by TSKimball** [comment]
Some update for the Genetics mini-line:

1) Remove 'Incubator Recipes' as its duplicated in 'Sequencing DNA.'  Move the book over though, its a nice cheat sheet after going through the machines.  Alternatively, move the Incubator part of Sequencing DNA back to this node.

2) Problems with sensing certain items, like the Incubator and Gene Database.  I've not re-opened the book in edit mode yet, so not sure if you can ignore NBT etc on the item(s).  But crafted Incubators are not seen either (tried vanilla table and AE terminal).  Perhaps some of these need 'detect' buttons?  They currently do not have it.

All the non-genetics tree breeding quests are working good.  One idea that did come to mind is to add mid-tier drones and saplings to Greater and Epic reward bags.  ;-)

**Comment by belathus** [comment]
Alright, I fixed the clockwork generator recipe. It now uses both types of gears. I changed the reward for the Specimen Chests quest as suggested. The balsa tree quest no longer has that requirement. I switched the order of the incubator recipe and the Sequencing DNA quest. I did not remove the Incubator Recipes, as not everything was covered in the Sequencing DNA quest, but I did remove the redundancy. I tried to put more detail about the multifarm's construction in the quest book, but I don't think I can do it justice in a quest book. And, finally, I made the quests that you mentioned "fuzzy". I also made the incubator quest to be a detection quest rather than a crafting quest, so you only need to have them in your inventory. There is also now a "manual detect" button due to its new status.
